apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
  labels:
    app: client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
      - name: client
        image: __IMAGE_NAME__:__IMAGE_TAG__
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        
---
apiVersion: v1
kind: Service
metadata:
  name: react
spec:
  selector:
    app: client
  ports:
  - name: http
    protocol: TCP
    port: 3000
  type: LoadBalancer
