
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: med00723/backend
        ports:
        - containerPort: 8081
        env:
        - name: MONGO_HOST
          value: mongo-service
        - name: MONGO_PORT
          value: "27017"
        

---

apiVersion: v1
kind: Service
metadata:
  name: webapp-service
spec:
  type: NodePort
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
     
